blueprint: ubuntu2004
ubuntu:
  playbook: ubuntu.yml
  command:
    # - "cat /root/root_secret.txt"
    # - "/home/guest/exploit.sh"
    # - "su - hacker -c \"cat /root/root_secret.txt\""
    - "echo happy"

