---
- name: Install bash 5.0.0 vulnerable to privilege escalation/change (CVE-2019-18276)
  hosts: all
  become: yes
  vars:
    bash_version: "5.0"
    install_dir: "/opt"

  become_user: root
  tasks:
    - name:
      ansible.builtin.user:
        name: victum
        uid: 1001
        create_home: yes

    - name:
      ansible.builtin.user:
        name: hacker
        uid: 1002
        create_home: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - build-essential
          - make

    - name: Copy vulnerable bash to target
      copy:
        src: "./data/bash-5.0.tar.gz"
        dest: "{{ install_dir }}/bash-{{ bash_version }}.tar.gz"


    - name: Extract vulnerable bash
      ansible.builtin.unarchive:
        src: "{{ install_dir }}/bash-{{ bash_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: Compile Bash from source
      command:
        cmd: "{{ item }}"
        chdir: "{{ install_dir }}/bash-{{ bash_version }}"
      loop:
        - ./configure
        - make

    - name: Change ownership of bash to victum
      file:
        path: "{{ install_dir }}/bash-{{ bash_version }}/bash"
        owner: victum
        mode: "4755"

    - name: Copy exploit to hacker user
      copy:
        src: "./data/bash50patch11-escalate.sh"
        dest: "/home/hacker/bash50patch11-escalate.sh"
        mode: "0755"
        owner: hacker

    - name: Copy top secret info to victum user
      copy:
        src: "./data/secret.txt"
        dest: "/home/victum/secret.txt"
        mode: "0600"
        owner: victum 

